export const COMENZAR_DESCARGA_HOTELES = 'COMENZAR_DESCARGA_PRODUCTOS';
export const DESCARGA_HOTELES_EXITOSA = 'DESCARGA_PRODUCTOS_EXITOSA';
export const DESCARGA_HOTELES_ERROR = 'DESCARGA_PRODUCTOS_ERROR';

export const COMENZAR_SELECCIONAR_HOTEL = 'COMENZAR_SELECCIONAR_HOTEL';
export const SELECCIONAR_HOTEL_EXITOSA = 'SELECCIONAR_HOTEL_EXITOSA';
export const SELECCIONAR_HOTEL_ERROR = 'SELECCIONAR_HOTEL_ERROR';

export const COMENZAR_BUSQUEDA_HOTELES = 'COMENZAR_BUSQUEDA_HOTELES';
export const BUSQUEDA_HOTELES_EXITOSA = 'BUSQUEDA_HOTELES_EXITOSA';
export const BUSQUEDA_HOTELES_ERROR = 'BUSQUEDA_HOTELES_ERROR';

